name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker tag
      id: vars
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image with token
      run: docker build --build-arg TOKEN=${{ secrets.TOKEN }} . --file Dockerfile --tag mavhub/stablediffusion:${{ env.IMAGE_TAG }}

    - name: Tag image as latest
      run: docker tag mavhub/stablediffusion:${{ env.IMAGE_TAG }} mavhub/stablediffusion:latest
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub with timestamp tag
      run: docker push mavhub/stablediffusion:${{ env.IMAGE_TAG }}

    - name: Push Docker image to Docker Hub with latest tag
      run: docker push mavhub/stablediffusion:latest
